version: '3'

services:
  newsnow:
    image: ghcr.io/ourongxing/newsnow:latest
    container_name: newsnow
    ports:
      - '4444:4444'
    volumes:
      - newsnow_data:/usr/app/.data
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.newsnow.rule=Host(${DOMAIN:-`newsnow.localhost}`)"
      - "traefik.http.routers.newsnow.entrypoints=web"
      - "traefik.http.services.newsnow.loadbalancer.server.port=4444"
      - "traefik.docker.network=dokploy-network"
   
networks:
  dokploy-network:
    external: true

volumes:
  newsnow_data:
    name: newsnow_data
